# Generated by Django 5.2.12 on 2026-03-12 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('result', models.CharField(blank=True, max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], default='patient', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('activity', models.CharField(blank=True, choices=[('laptop', 'Working on laptop'), ('desktop', 'Desktop work'), ('phone', 'Using phone'), ('studying', 'Studying'), ('gaming', 'Gaming')], max_length=50)),
                ('sitting_hours', models.CharField(blank=True, choices=[('1-3', '1–3 hours'), ('4-6', '4–6 hours'), ('7-9', '7–9 hours'), ('10+', '10+ hours')], max_length=20)),
                ('exercise_habit', models.CharField(blank=True, choices=[('regular', 'Yes regularly'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never')], max_length=20)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='PhysioTrack.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
