# Generated by Django 5.2.12 on 2026-03-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhysioTrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posturevideo',
            name='video',
        ),
        migrations.AddField(
            model_name='posturevideo',
            name='image',
            field=models.FileField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
